[package]
name = "xcrypt-sys"
description = "Low-level bindings for libxcrypt"
version = "0.1.0"
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[build-dependencies]
bindgen = "0.70.1"
