[package]
name = "xcrypt"
description = "Bindings for libxcrypt"
version = "0.1.0"
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
xcrypt-sys = "0.1.0"

[lints]
workspace = true
